version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm
      - goos: windows
        goarch: 386

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: yodamad
    name: heimdall
  draft: false
  prerelease: auto
  make_latest: true
  replace_existing_draft: true
  name_template: 'v{{ .Tag }}'
  header: |

  footer: |
    ## Enjoy 🍹
    📆 {{ .Now.Format "2006-01-02" }} - Copyright @yodamad

brews:
  - name: heimdall
    homepage: https://github.com/yodamad/heimdall
    commit_author:
      name: yodamad
      email: mvincent.it@gmail.com
    license: MIT
    url_template: "https://github.com/yodamad/heimdall/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    dependencies:
      - name: git
      - name: zsh
        type: optional
    repository:
      owner: yodamad
      name: homebrew-tools
      branch: main

