name: Release
run-name: Release ${{ github.event.inputs.tag }}
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag name (starting with a `v`)'
        required: true

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
      - run: git tag ${{ github.event.inputs.tag }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag }}
      -
        name: Set up Go for publishing
        uses: actions/setup-go@v5
      -
        name: Publish to pkg.go.dev
        run:  |
          GOPROXY=proxy.golang.org go list -m github.com/yodamad/heimdall@${{ github.event.inputs.tag }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          cd site
          pip install -r requirements.txt
          mkdocs gh-deploy --force