name: release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag name'
        required: true

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
      - run: git tag ${{ github.event.inputs.tag }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      -
        name: Publish to pkg.go.dev
        run:  |
          git checkout {{ github.event.inputs.tag }}
          GOPROXY=proxy.golang.org go list -m github.com/yodamad/heimdall@${{ github.event.inputs.tag }}
